import { useMemo, useState, type FormEvent } from 'react';
import { api } from '../api/api';
import type { BankAccount, Bill, Category, CreditCard, Expense, Invoice, Person } from '../api/types';
import { useMonth, useRefresh } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import { monthRange, toLocalDateTime, todayIso } from '../utils/date';
import { parseCurrencyToCents, validateAllocation } from '../utils/money';
import { useLoad } from '../hooks/useLoad';
import { Button, CurrencyInput, FormField } from './ui';

type Done = { onDone: () => void };
function useSubmit(onDone: () => void) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const notify = useToast(); const { refresh } = useRefresh();
  const submit = async (action: () => Promise<unknown>, success: string) => { if (saving) return; setSaving(true); setError(''); try { await action(); notify(success); refresh(); onDone(); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Não foi possível salvar.'; setError(message); notify(message, 'error'); } finally { setSaving(false); } };
  return { submit, saving, error, setError };
}
function Options({ values, placeholder = 'Selecione…' }: { values?: Array<{ id: number; name: string }>; placeholder?: string }) { return <><option value="">{placeholder}</option>{values?.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</>; }
function FormFooter({ saving, onDone, error, label = 'Salvar' }: { saving: boolean; onDone: () => void; error?: string; label?: string }) { return <>{error && <div className="form-error" role="alert">{error}</div>}<div className="form-actions"><Button type="button" variant="outline" onClick={onDone}>Cancelar</Button><Button type="submit" variant="primary" disabled={saving}>{saving ? 'Salvando…' : label}</Button></div></>; }
function useReferences() {
  const { year, month } = useMonth(); const range = monthRange(year, month);
  return useLoad(async () => { const [people, categories, accounts, cards, invoices, bills, expenses] = await Promise.all([api.people.list(true), api.categories.list(undefined, true), api.accounts.list(true), api.cards.list(true), api.invoices.list(year, month), api.bills.list(year, month), api.expenses.list(range.from, range.to)]); return { people, categories, accounts, cards, invoices, bills, expenses }; }, [year, month]);
}

export function BillForm({ onDone }: Done) {
  const refs = useReferences(); const { year, month } = useMonth(); const mutation = useSubmit(onDone); const [amount, setAmount] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void mutation.submit(() => api.bills.create({ name: form.get('name'), categoryId: Number(form.get('categoryId')), responsiblePersonId: Number(form.get('responsiblePersonId')), referenceYear: year, referenceMonth: month, expectedAmountCents: parseCurrencyToCents(amount), dueDate: form.get('dueDate') }), 'Conta cadastrada.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Nome"><input className="input" name="name" required /></FormField><FormField label="Categoria"><select className="input" name="categoryId" required><Options values={refs.data?.categories.filter((c) => c.type === 'EXPENSE')} /></select></FormField><FormField label="Responsável"><select className="input" name="responsiblePersonId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Vencimento"><input className="input" name="dueDate" type="date" required /></FormField><FormField label="Valor previsto" full><CurrencyInput value={amount} onChange={setAmount} required /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Salvar conta" /></form>;
}

export function ExpenseForm({ onDone }: Done) {
  const refs = useReferences(); const mutation = useSubmit(onDone); const [amount, setAmount] = useState(''); const [mode, setMode] = useState<'one' | 'split'>('one'); const [person, setPerson] = useState(''); const [splits, setSplits] = useState<Record<number, string>>({});
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); let total: number; try { total = parseCurrencyToCents(amount); } catch (e) { mutation.setError((e as Error).message); return; }
    const allocations = mode === 'one' ? [{ personId: Number(person), amountCents: total }] : Object.entries(splits).filter(([, value]) => value.trim()).map(([id, value]) => ({ personId: Number(id), amountCents: parseCurrencyToCents(value) }));
    if (!person && mode === 'one') { mutation.setError('Escolha quem é responsável pela compra.'); return; }
    const allocationError = validateAllocation(total, allocations.map((a) => a.amountCents)); if (allocationError) { mutation.setError(allocationError); return; }
    const form = new FormData(event.currentTarget); void mutation.submit(() => api.expenses.create({ description: form.get('description'), categoryId: Number(form.get('categoryId')), amountCents: total, scope: form.get('scope'), occurredAt: toLocalDateTime(String(form.get('date'))), creditCardInvoiceId: form.get('invoiceId') ? Number(form.get('invoiceId')) : null, notes: form.get('notes') || null, allocations }), 'Despesa registrada.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Descrição"><input className="input" name="description" placeholder="Ex.: Mercado do mês" required /></FormField><FormField label="Categoria"><select className="input" name="categoryId" required><Options values={refs.data?.categories.filter((c) => c.type === 'EXPENSE')} /></select></FormField><FormField label="Valor"><CurrencyInput value={amount} onChange={setAmount} required /></FormField><FormField label="Data"><input className="input" name="date" type="date" defaultValue={todayIso()} required /></FormField><FormField label="Onde entra este gasto?"><select className="input" name="scope"><option value="HOUSEHOLD">Casa</option><option value="PERSONAL">Pessoal</option></select></FormField><FormField label="Fatura (opcional)"><select className="input" name="invoiceId"><Options values={refs.data?.invoices.map((invoice) => ({ id: invoice.id, name: `${invoice.creditCard.name} · ${invoice.referenceMonth}/${invoice.referenceYear}` }))} placeholder="Fora do cartão" /></select></FormField><fieldset className="fieldset"><legend>Quem é responsável por esta compra?</legend><p className="muted">A divisão precisa somar exatamente o valor total.</p><div className="radio-row"><label><input type="radio" checked={mode === 'one'} onChange={() => setMode('one')} /> Uma pessoa</label><label><input type="radio" checked={mode === 'split'} onChange={() => setMode('split')} /> Dividir</label></div></fieldset>{mode === 'one' ? <FormField label="Pessoa responsável" full><select className="input" value={person} onChange={(e) => setPerson(e.target.value)} required><Options values={refs.data?.people} /></select></FormField> : <div className="allocation-box"><strong>Valores por pessoa</strong>{refs.data?.people.map((item) => <div className="allocation-row" key={item.id}><label htmlFor={`split-${item.id}`}>{item.name}</label><CurrencyInput id={`split-${item.id}`} value={splits[item.id] ?? ''} onChange={(value) => setSplits((all) => ({ ...all, [item.id]: value }))} /></div>)}</div>}<FormField label="Observação (opcional)" full><textarea className="input textarea" name="notes" /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Salvar despesa" /></form>;
}

export function IncomeForm({ onDone }: Done) {
  const refs = useReferences(); const mutation = useSubmit(onDone); const [amount, setAmount] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void mutation.submit(() => api.incomes.create({ personId: Number(form.get('personId')), bankAccountId: form.get('accountId') ? Number(form.get('accountId')) : null, categoryId: Number(form.get('categoryId')), description: form.get('description'), amountCents: parseCurrencyToCents(amount), expectedDate: form.get('expectedDate') }), 'Renda cadastrada.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Descrição"><input className="input" name="description" required /></FormField><FormField label="Categoria"><select className="input" name="categoryId" required><Options values={refs.data?.categories.filter((c) => c.type === 'INCOME')} /></select></FormField><FormField label="Pessoa"><select className="input" name="personId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Conta bancária (opcional)"><select className="input" name="accountId"><Options values={refs.data?.accounts} /></select></FormField><FormField label="Valor"><CurrencyInput value={amount} onChange={setAmount} required /></FormField><FormField label="Data prevista"><input className="input" type="date" name="expectedDate" defaultValue={todayIso()} required /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Salvar renda" /></form>;
}

export function PaymentForm({ onDone, defaultTarget, defaultId }: Done & { defaultTarget?: 'bill' | 'invoice' | 'expense'; defaultId?: number }) {
  const refs = useReferences(); const mutation = useSubmit(onDone); const [amount, setAmount] = useState(''); const [target, setTarget] = useState(defaultTarget ?? 'bill');
  const targets = useMemo(() => target === 'bill' ? refs.data?.bills.filter((b) => b.status !== 'PAID' && b.status !== 'CANCELLED').map((b) => ({ id: b.id, name: b.name })) : target === 'invoice' ? refs.data?.invoices.map((i) => ({ id: i.id, name: i.creditCard.name })) : refs.data?.expenses.map((e) => ({ id: e.id, name: e.description })), [refs.data, target]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const id = Number(form.get('targetId')); void mutation.submit(() => api.payments.create({ payerPersonId: Number(form.get('payerPersonId')), bankAccountId: form.get('accountId') ? Number(form.get('accountId')) : null, method: form.get('method'), amountCents: parseCurrencyToCents(amount), paidAt: toLocalDateTime(String(form.get('date'))), expenseId: target === 'expense' ? id : null, householdBillId: target === 'bill' ? id : null, creditCardInvoiceId: target === 'invoice' ? id : null, notes: form.get('notes') || null }), 'Pagamento registrado.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="O que foi pago?"><select className="input" value={target} onChange={(e) => setTarget(e.target.value as typeof target)}><option value="bill">Conta da casa</option><option value="invoice">Fatura</option><option value="expense">Despesa</option></select></FormField><FormField label="Item"><select className="input" name="targetId" defaultValue={defaultId} key={`${target}-${defaultId}`} required><Options values={targets} /></select></FormField><FormField label="Quem pagou"><select className="input" name="payerPersonId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Conta usada (opcional)"><select className="input" name="accountId"><Options values={refs.data?.accounts} /></select></FormField><FormField label="Forma de pagamento"><select className="input" name="method"><option value="PIX">Pix</option><option value="BOLETO">Boleto</option><option value="DEBIT">Débito</option><option value="CASH">Dinheiro</option><option value="TRANSFER">Transferência</option><option value="OTHER">Outro</option></select></FormField><FormField label="Valor"><CurrencyInput value={amount} onChange={setAmount} required /></FormField><FormField label="Data"><input className="input" type="date" name="date" defaultValue={todayIso()} required /></FormField><FormField label="Observação" full><input className="input" name="notes" /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Registrar pagamento" /></form>;
}

export function SettlementForm({ onDone }: Done) {
  const refs = useReferences(); const mutation = useSubmit(onDone); const [amount, setAmount] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('fromPersonId') === form.get('toPersonId')) { mutation.setError('Escolha pessoas diferentes.'); return; } void mutation.submit(() => api.settlements.create({ fromPersonId: Number(form.get('fromPersonId')), toPersonId: Number(form.get('toPersonId')), amountCents: parseCurrencyToCents(amount), paidAt: toLocalDateTime(String(form.get('date'))), notes: form.get('notes') || null }), 'Acerto registrado.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Quem pagou"><select className="input" name="fromPersonId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Quem recebeu"><select className="input" name="toPersonId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Valor"><CurrencyInput value={amount} onChange={setAmount} required /></FormField><FormField label="Data"><input className="input" type="date" name="date" defaultValue={todayIso()} required /></FormField><FormField label="Observação" full><input className="input" name="notes" /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Registrar acerto" /></form>;
}

export function CardForm({ onDone }: Done) {
  const refs = useReferences(); const mutation = useSubmit(onDone); const [limit, setLimit] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); void mutation.submit(() => api.cards.create({ name:f.get('name'), institution:f.get('institution'), holderId:Number(f.get('holderId')), invoicePayerId:Number(f.get('invoicePayerId')), defaultResponsiblePersonId:Number(f.get('defaultResponsiblePersonId')), lastFour:f.get('lastFour') || null, creditLimitCents:parseCurrencyToCents(limit), closingDay:Number(f.get('closingDay')), dueDay:Number(f.get('dueDay')) }), 'Cartão cadastrado.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Nome"><input className="input" name="name" required /></FormField><FormField label="Instituição"><input className="input" name="institution" required /></FormField><FormField label="Titular"><select className="input" name="holderId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Quem paga esta fatura"><select className="input" name="invoicePayerId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Responsável padrão"><select className="input" name="defaultResponsiblePersonId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Últimos 4 dígitos"><input className="input" name="lastFour" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} /></FormField><FormField label="Limite"><CurrencyInput value={limit} onChange={setLimit} required /></FormField><FormField label="Fechamento"><input className="input" name="closingDay" type="number" min="1" max="31" required /></FormField><FormField label="Vencimento"><input className="input" name="dueDay" type="number" min="1" max="31" required /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Salvar cartão" /></form>;
}

export function InvoiceForm({ onDone, card }: Done & { card?: CreditCard }) {
  const refs = useReferences(); const { year, month } = useMonth(); const mutation = useSubmit(onDone); const [reported, setReported] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); void mutation.submit(() => api.invoices.create({ creditCardId:Number(f.get('cardId')), referenceYear:year, referenceMonth:month, dueDate:f.get('dueDate'), reportedTotalCents:reported ? parseCurrencyToCents(reported) : null }), 'Fatura criada.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Cartão"><select className="input" name="cardId" defaultValue={card?.id} required><Options values={refs.data?.cards} /></select></FormField><FormField label="Vencimento"><input className="input" type="date" name="dueDate" required /></FormField><FormField label="Total informado (opcional)" full><CurrencyInput value={reported} onChange={setReported} /></FormField><FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} label="Criar fatura" /></form>;
}

export function SetupForm({ kind, onDone }: Done & { kind: 'person' | 'category' | 'account' }) {
  const refs = useReferences(); const mutation = useSubmit(onDone); const [balance, setBalance] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const action = kind === 'person' ? () => api.people.create({ name:String(f.get('name')), type:String(f.get('type')) }) : kind === 'category' ? () => api.categories.create({ name:String(f.get('name')), type:String(f.get('type')) }) : () => api.accounts.create({ name:f.get('name'), institution:f.get('institution'), ownerId:Number(f.get('ownerId')), initialBalanceCents:parseCurrencyToCents(balance) }); void mutation.submit(action, kind === 'person' ? 'Pessoa cadastrada.' : kind === 'category' ? 'Categoria cadastrada.' : 'Conta bancária cadastrada.'); };
  return <form className="form-grid" onSubmit={submit}><FormField label="Nome"><input className="input" name="name" required /></FormField>{kind === 'person' && <FormField label="Participação"><select className="input" name="type"><option value="USER">Usuário</option><option value="EXTERNAL">Contato externo</option></select></FormField>}{kind === 'category' && <FormField label="Usada para"><select className="input" name="type"><option value="EXPENSE">Despesas</option><option value="INCOME">Rendas</option></select></FormField>}{kind === 'account' && <><FormField label="Instituição"><input className="input" name="institution" required /></FormField><FormField label="Titular"><select className="input" name="ownerId" required><Options values={refs.data?.people} /></select></FormField><FormField label="Saldo inicial"><CurrencyInput value={balance} onChange={setBalance} required /></FormField></>}<FormFooter saving={mutation.saving} onDone={onDone} error={mutation.error} /></form>;
}
