import { useState } from 'react';
import { api } from '../api/api';
import type { Bill } from '../api/types';
import { PageHeader } from '../components/PageHeader';
import { BillForm, PaymentForm } from '../components/forms';
import { Button, ChoiceTabs, CurrencyInput, EmptyState, ErrorState, LoadingState, Modal, StatusBadge } from '../components/ui';
import { useMonth, useRefresh } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import { useLoad } from '../hooks/useLoad';
import { formatDate } from '../utils/date';
import { formatCurrency, parseCurrencyToCents } from '../utils/money';

export function BillsPage() {
  const { year, month } = useMonth(); const { refresh } = useRefresh(); const notify = useToast(); const [filter, setFilter] = useState('all'); const [modal, setModal] = useState<'create' | 'payment' | 'amount'>(); const [selected, setSelected] = useState<Bill>(); const [amount, setAmount] = useState(''); const [saving, setSaving] = useState(false);
  const state = useLoad(() => api.bills.list(year, month), [year, month]); const bills = state.data ?? []; const visible = bills.filter((bill) => filter === 'all' || filter === 'pending' ? (filter === 'all' || !['PAID','CANCELLED'].includes(bill.status)) : bill.status === 'PAID');
  const paid = bills.reduce((sum,b) => sum + b.paidAmountCents,0), total = bills.reduce((sum,b) => sum + b.effectiveAmountCents,0);
  const cancel = async (bill: Bill) => { if (!window.confirm(`Cancelar a conta “${bill.name}”?`)) return; setSaving(true); try { await api.bills.cancel(bill.id); notify('Conta cancelada.'); refresh(); } catch(e){notify((e as Error).message,'error')} finally{setSaving(false)} };
  const adjust = async () => { if (!selected || saving) return; setSaving(true); try { await api.bills.amount(selected.id,{actualAmountCents:parseCurrencyToCents(amount)}); notify('Valor atualizado.'); setModal(undefined); refresh(); } catch(e){notify((e as Error).message,'error')} finally{setSaving(false)} };
  return <><PageHeader title="Contas do mês" subtitle="Acompanhe o que vence, o que foi pago e o que ainda está pendente." actionLabel="+ Nova conta" onAction={() => setModal('create')} /><section className="summary-grid"><Summary label="Total do mês" value={total}/><Summary label="Pago" value={paid}/><Summary label="Em aberto" value={total-paid}/></section><section className="card list-card"><div className="list-heading"><div><h2 className="panel-title">{new Intl.DateTimeFormat('pt-BR',{month:'long'}).format(new Date(year,month-1))}</h2><p className="panel-subtitle">{bills.length} contas cadastradas</p></div><ChoiceTabs value={filter} onChange={setFilter} items={[{value:'all',label:'Todas'},{value:'pending',label:'Pendentes'},{value:'paid',label:'Pagas'}]} /></div>{state.loading ? <LoadingState/> : state.error ? <ErrorState message={state.error} retry={state.reload}/> : !visible.length ? <EmptyState title="Nenhuma conta por aqui" text="Cadastre uma conta da casa ou altere o filtro."/> : <ul className="row-list">{visible.map((bill)=><li className="data-row" key={bill.id}><div><span className="row-primary">{bill.name}</span><span className="row-secondary">Vence {formatDate(bill.dueDate)} · {bill.responsiblePerson.name}</span></div><div><strong>{formatCurrency(bill.effectiveAmountCents)}</strong><span className="row-secondary">Pago {formatCurrency(bill.paidAmountCents)} · falta {formatCurrency(bill.outstandingAmountCents)}</span></div><StatusBadge status={bill.status} danger={bill.overdue}/><div className="actions">{!['PAID','CANCELLED'].includes(bill.status)&&<Button onClick={()=>{setSelected(bill);setModal('payment')}}>Pagar</Button>}<button className="link-button" onClick={()=>{setSelected(bill);setAmount('');setModal('amount')}}>Ajustar valor</button>{bill.status!=='CANCELLED'&&<button disabled={saving} className="link-button" onClick={()=>void cancel(bill)}>Cancelar</button>}</div></li>)}</ul>}</section>{modal==='create'&&<Modal title="Nova conta" subtitle="Adicione uma conta da casa para este mês." onClose={()=>setModal(undefined)}><BillForm onDone={()=>setModal(undefined)}/></Modal>}{modal==='payment'&&selected&&<Modal title="Registrar pagamento" subtitle={selected.name} onClose={()=>setModal(undefined)}><PaymentForm defaultTarget="bill" defaultId={selected.id} onDone={()=>setModal(undefined)}/></Modal>}{modal==='amount'&&selected&&<Modal title="Ajustar valor" subtitle="Informe o valor real desta conta." onClose={()=>setModal(undefined)} small><div className="form-grid"><div className="form-field full"><label htmlFor="bill-amount">Valor real</label><CurrencyInput id="bill-amount" value={amount} onChange={setAmount}/></div><div className="form-actions"><Button variant="outline" onClick={()=>setModal(undefined)}>Cancelar</Button><Button variant="primary" disabled={saving} onClick={()=>void adjust()}>Salvar</Button></div></div></Modal>}</>;
}
function Summary({label,value}:{label:string;value:number}){return <article className="card summary-card"><span className="muted">{label}</span><strong>{formatCurrency(value)}</strong></article>}
