import { api } from '../api/api';
import { useMonth } from '../context/AppContext';
import { useRegistry } from '../context/RegistryContext';
import { useLoad } from '../hooks/useLoad';
import { formatDate } from '../utils/date';
import { formatCurrency } from '../utils/money';
import { longMonth } from '../components/MonthSelector';
import { PageHeader } from '../components/PageHeader';
import { Button, EmptyState, ErrorState, LoadingState, StatusBadge } from '../components/ui';
import { useNavigate } from 'react-router-dom';

export function DashboardPage() {
  const { year, month } = useMonth(); const openRegistry = useRegistry(); const navigate = useNavigate();
  const state = useLoad(async () => { const [overview, bills, invoices] = await Promise.all([api.overview.monthly(year, month), api.overview.bills(year, month), api.overview.invoices(year, month)]); return { overview, bills, invoices }; }, [year, month]);
  if (state.loading) return <><PageHeader title="Seu mês em um só lugar" subtitle={longMonth(year, month)} onAction={openRegistry} /><LoadingState /></>;
  if (state.error || !state.data) return <><PageHeader title="Seu mês em um só lugar" subtitle={longMonth(year, month)} onAction={openRegistry} /><ErrorState message={state.error} retry={state.reload} /></>;
  const { overview, bills, invoices } = state.data; const empty = !overview.income.expectedCents && !overview.householdBills.totalCents && !overview.creditCards.totalCents && !bills.length && !invoices.length;
  const overdue = bills.filter((bill) => bill.overdue);
  return <><PageHeader title="Seu mês em um só lugar" subtitle={longMonth(year, month)} onAction={openRegistry} />{empty ? <div className="card"><EmptyState /></div> : <><section className="stats-grid" aria-label="Resumo do mês"><Stat label="Entradas recebidas" value={overview.income.receivedCents} detail={`de ${formatCurrency(overview.income.expectedCents)} esperados`} /><Stat label="Contas da casa" value={overview.householdBills.totalCents} detail={`${formatCurrency(overview.householdBills.outstandingCents)} ainda em aberto`} /><Stat label="Cartões" value={overview.creditCards.totalCents} detail={`${invoices.length} ${invoices.length === 1 ? 'fatura' : 'faturas'} neste mês`} /><Stat label="Ainda a pagar" value={overview.householdBills.outstandingCents + overview.creditCards.outstandingCents} detail={`${overdue.length} ${overdue.length === 1 ? 'conta precisa' : 'contas precisam'} de atenção`} /></section>{overdue.length > 0 && <section className="alert card"><span className="alert-icon">!</span><div className="alert-copy"><strong>{overdue.length} {overdue.length === 1 ? 'conta está atrasada' : 'contas estão atrasadas'}</strong><span>{overdue.slice(0, 2).map((bill) => `${bill.name} venceu em ${formatDate(bill.dueDate)}`).join(' e ')}.</span></div><Button className="danger" onClick={() => navigate('/bills')}>Ver contas</Button></section>}<div className="dashboard-columns"><section className="card panel"><header className="panel-header"><div><h2 className="panel-title">Próximas contas</h2><p className="panel-subtitle">O que precisa da sua atenção neste mês</p></div><Button onClick={() => navigate('/bills')}>Ver todas</Button></header>{bills.length ? <ul className="row-list">{bills.slice(0, 6).map((bill) => <li className="data-row" key={bill.id}><div><span className="row-primary">{bill.name}</span><span className="row-secondary">Vence {formatDate(bill.dueDate)}</span></div><strong>{formatCurrency(bill.effectiveAmountCents)}</strong><StatusBadge status={bill.status} danger={bill.overdue} /></li>)}</ul> : <EmptyState title="Nenhuma conta neste mês" text="Use Registrar para adicionar a primeira conta da casa." />}</section><section className="card panel"><header className="panel-header"><div><h2 className="panel-title">Faturas</h2><p className="panel-subtitle">{longMonth(year, month).split(' de ')[0]}</p></div></header>{invoices.length ? invoices.map((invoice) => <article className="invoice-tile" key={invoice.id}><strong>{invoice.cardName}</strong><b>{formatCurrency(invoice.calculatedTotalCents)}</b><span className="row-secondary">{invoice.outstandingAmountCents ? `${formatCurrency(invoice.outstandingAmountCents)} restante` : 'Paga'}</span></article>) : <EmptyState title="Nenhuma fatura" text="Crie cartões e faturas para acompanhar suas compras." />}</section></div></>}</>;
}
function Stat({ label, value, detail }: { label: string; value: number; detail: string }) { return <article className="card stat-card"><span className="stat-dot" aria-hidden="true" /><span className="stat-label">{label}</span><h2 className="stat-value">{formatCurrency(value)}</h2><span className="muted">{detail}</span></article>; }
